const Sequelize = require('sequelize')
const db = require('./database')

const Coder = db.define('student', {
    candidate_id: {
        type: Sequelize.INTEGER,
        allowNull: false
    },
    communication_score: {
        type: Sequelize.INTEGER,
        allowNull: false
    },
    coding_score: {
        type: Sequelize.INTEGER,
        allowNull: false
    },
    title: {
        type: Sequelize.ENUM('Engineer', 'Senior Engineer'),
        allowNull: false
    },
    company_id: {
        type: Sequelize.INTEGER
    }

})
//In the case where is app were to be scaled up and include a separate table for comapnies, company_id wouldn't be created here in the model
// instead, it would be generated by sequelize as a foreign key through the many to one relation which would be established in db/index.js
//
//I am allowing comany_id to be null because I imagine a case where an eningeer might be between companies, even though this does not exist in our seed data

module.exports = Coder
